/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Scala library project to get you started.
 * For more details take a look at the Scala plugin chapter in the Gradle
 * User Manual available at https://docs.gradle.org/5.6.2/userguide/scala_plugin.html
 */
import org.gradle.api.tasks.testing.logging.TestLogEvent.*

//import "com.github.jengelman.gradle.plugins.shadow.ShadowExtension"
//import "com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar"

val scalaVersion = "2.12"

plugins {
    // Apply the scala plugin to add support for Scala
    scala
}

allprojects {
    apply(plugin = "idea")

    repositories {
        // Use jcenter for resolving dependencies.
        // You can declare any Maven/Ivy/file repository here.
        jcenter()
    }
}

subprojects {
    apply(plugin = "scala")
    group = "scalachess"
    version = "0.1"

    dependencies {
        implementation("org.scala-lang:scala-library:$scalaVersion.8")
        // Use Scalatest for testing our library
        testImplementation("junit:junit:4.12")
        testImplementation("org.scalatest:scalatest_2.12:3.0.8")

        // Need scala-xml at test runtime
        testRuntimeOnly("org.scala-lang.modules:scala-xml_2.12:1.2.0")
    }

    tasks {
        register("copyDeps", Copy::class) {
            from("configuration.runtime")
            into("build/dependencies")
        }
    }
}

project("core") {
    dependencies {
//        "implementation"("org.scala-lang:scala-library:$scalaVersion.8")
    }
}

project("client") {

    apply(plugin = "application")

    dependencies {
        "implementation"(project(":core"))
    }

    configure<ApplicationPluginConvention> {
        mainClassName = "it.scalachess.client.Client"
    }
}

defaultTasks("clean", "build")
